server:
  port: 9000
spring:
  application:
    name: consumer
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:2222/eureka/