server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.232.128:1111
    sentinel:
      transport:
        dashboard: 192.168.232.128:8080
        port: 8719

service-uri:
  nacos-user-service: http://nacos-payment-provider

feign:
  sentinel:
    enabled: true