server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.232.128:1111
    sentinel:
      transport:
        dashboard: 192.168.232.128:8080
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'