server:
  port: 7003

spring:
  application:
    name:
eureka:
  instance:
    hostname: eureka7003.com # eureka服务实例名称
  client:
    # 不注册自己
    register-with-eureka: false
    # false 表示注册中心，职责就是维护服务实例
    fetch-registry: false
    service-url:
      # eureka 服务注册和查询地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/